<hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
   <script src="vue/js/jquery.js"></script>
 
    <script src="vue/js/jquery.raty.js"></script>
     
 
    <script src="vue/js/app.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vue/js/bootstrap.min.js"></script>
    
    <script src="vue/js/bootstrap-datepicker.js"></script>

</body>

</html>