<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="vue/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

    <!-- Custom CSS -->
    <link href="vue/css/blog-home.css" rel="stylesheet">

    <link href="vue/css/bootstrap-datepicker.css" rel="stylesheet">
    

    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script>
        $(function() {
            $("#datepicker").datepicker(
                {
                    dateFormat:"yy-mm-dd"
                });
        });
    </script>

    <link href="vue/css/signin.css" rel="stylesheet">
    
    <style text="text/css">    

        #tt{
            margin-bottom: 10px;
            margin-top: 10px;
        }

         #tt1{
            margin-bottom: 10px;
          
        }

          #tt2{
            margin-bottom: 10px;
          
        }

          #tt3{
            margin-bottom: 10px;
          
        }

        #tt33{
            margin-bottom: 10px;
          
        }

          #tt4{
            margin-bottom: 10px;
          
        }

    
        .jpf1{
            background-color: lightgrey;
            width: 20%;
            text-align: center;
            margin-left: 400px;
            margin-top: 50px;
            }

            p{
                margin-top:20px;
            }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Accueil</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                   
                    <li>
                        <a href="index.php?page=categories">Categories</a>
                    </li>
                    
                    <?php if (isConnected()) : ?>

                        <li>
                            <a href="index.php?page=statistiques">Statistiques</a>
                        </li>
                    
                    <?php endif; ?>


                     <?php if (isConnected()) : ?>

                        <li>
                            <a href="index.php?page=logout">Logout</a>
                        </li>

                     <?php else : ?>

                        <li>
                            <a href="index.php?page=login">Login</a>
                        </li>

                   <?php endif ;?>

                   
                        <li>
                            <a href="index.php?page=ajoutArticle">AjoutArticle</a>
                        </li>
                    
                         <li>
                            <a href="index.php?page=ajoutCategorie">AjoutCategorie</a>
                        </li>
                    


                     
                         <?php if (isConnected()) : ?>

                        <li><a>bienvenue <?php echo $_SESSION["utilisateur"]["login"]; ?></a></li>

                         <?php endif; ?>

                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>