   <?php

    /*$dsn = "mysql: host=localhost;dbname=blogtroiswa;charset=utf8";
    $login="root";
    $motDePasse = "troiswa";
    $connexion = new PDO($dsn, $login, $motDePasse);

    //Afiichage des erreurs
    $connexion->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING);*/

    $sql = "SELECT * FROM categorie";
    $requete = $connexion->prepare($sql);

    //$requete->bindvalue(":identifiant", $_GET["id"], PDO::PARAM_INT);
    $success = $requete->execute();
    // Recuperation des resultats dans une variable
    $sidebarcategories = $requete->fetchAll(PDO::FETCH_ASSOC);

    //var_dump($sidebarcategories);

    $reste =  count($sidebarcategories)/2;
    $reste  = ceil($reste); 

    //echo $reste;

    $tab = array_splice($sidebarcategories , $reste);

    //var_dump($sidebarcategories);
    //var_dump($tab);
    


?>


   <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">

                    <form method="GET" action ="index.php" autocomplete="off">

                        <input type="text" class="form-control" name="word" id="inputSearch">
                        <input type="hidden" class="form-control" name="page" value="recherche">
                        

                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    
                    </form>

                    <ul id="resultatRecherche">
                    </ul>

             

                        <?php if ( array_key_exists("word", $_GET) == true ) : ?>

                          <ul id="resultatRecherche">

                         <!-- <?php foreach ($articlerechercher as $key => $value) : ?>
                        
                            <li>
                                <a href=""><?php echo $value["titre"]; ?></a>
                            </li>

                         <?php  endforeach; ?> -->
                        
                         </ul>

                     <?php endif; ?>

                  
                        
                    


                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                 <?php foreach ($sidebarcategories  as $key => $value) : ?>
                                    
                                    <li><a href="#"><?php echo $value['nom']; ?></a>
                                    </li>
                               
                                   <?php  endforeach;  ?> 
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                  <?php foreach ($tab  as $key => $value) : ?>
                                     <li><a href="#"><?php echo $value['nom']; ?></a>
                                    </li>
                                 <?php  endforeach;  ?> 
                                
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>