


<?php 
  include "globals/header.phtml"; ?>

  <body>

    <div class="container">

      <form class="form-signin" method="POST" action="">

        <h2 class="form-signin-heading">Please sign in</h2>

        <label for="inputEmail" class="sr-only">Email address</label>
        
        <input type="text"  name="inputEmail" id="inputEmail" class="form-control" placeholder="Email address" autofocus>
        
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password"  name ="inputPassword" id="inputPassword" class="form-control" placeholder="Password" >
        
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>
