<?php 

include "globals/header.phtml"; ?>

    <!-- Page Content -->
   <!-- <p>Nombre d'articles: <?php echo $nbarticles; ?></p>  -->

     <p>Nombre d'articles: <?php echo $nbarticles['nb']; ?></p> 

       <p>Nombre de categories: <?php echo $nbcategories['nb']; ?></p> 


        <p>Meilleur article - titre: <?php echo $var1; ?></p> 
        <p>Meilleur article - note: <?php echo $var2; ?></p> 

<p>Meilleur categorie - titre: <?php echo $var3; ?></p> 
        <p>Meilleur categorie - note: <?php echo $var4; ?></p> 

      
   

      <?php  include "globals/footer.phtml"; ?>
