  <?php 

include "globals/header.phtml"; ?>

 <div class="col-lg-8">
 <div class="row">

    <?php foreach ($unecategorie  as $key => $value) : ?>

        <div class="col-lg-4">
          <img class="img-circle" src="vue/images/<?php echo $value['image']; ?>" alt="Generic placeholder image." width="140" height="140">
          <h2><?php echo $value["titre"]."<br/>"; ?></h2>
          <p><?php echo $value["description"]."<br/>"; ?></p>
          <p><a class="btn btn-default" href="index.php?page=article&id=<?php echo $value["id"]; ?>" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

    <?php  endforeach;  ?>  
   
      </div><!-- /.row -->
       </div>

  <?php 

      include "globals/sidebar.phtml"; ?>

    
       <?php  include "globals/footer.phtml"; ?>
